name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Check code formatting
        run: |
          git ls-files '*.sh' \
            | tee /dev/stderr \
            | xargs nix run .#shfmt -- --diff

      - name: Lint code
        run: |
          git ls-files '*.sh' \
            | tee /dev/stderr \
            | xargs nix run .#shellcheck --

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: true
          base-path-to-features: ./src

  list-features:
    name: List features
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      features: ${{ steps.list.outputs.features }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: List features
        id: list
        run: |
          # Make JSON list of all features; e.g. ["kubernetes-tools","openapi-generator-cli","opentofu"]
          features="$( \
            git ls-files './src/*/devcontainer-feature.json' \
            | xargs --replace='{}' sh -c 'basename "$(dirname "{}")"' \
            | jq --raw-input . \
            | jq --slurp --compact-output .
          )"

          echo "features=${features}" | tee --append "$GITHUB_OUTPUT"

  test-autogenerated:
    name: Test (autogenerated)
    needs: list-features
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJson(needs.list-features.outputs.features) }}
        baseImage: [debian:latest]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install latest devcontainer CLI
        run: npm install --global @devcontainers/cli

      - name: Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'
        run: devcontainer features test --skip-scenarios --features ${{ matrix.features }} --base-image ${{ matrix.baseImage }} .

  test-scenarios:
    name: Test (scenarios)
    needs: list-features
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJson(needs.list-features.outputs.features) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install latest devcontainer CLI
        run: npm install --global @devcontainers/cli

      - name: Generating tests for '${{ matrix.features }}' scenarios
        run: devcontainer features test --features ${{ matrix.features }} --skip-autogenerated --skip-duplicated .

  test-global:
    name: Test (global)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install latest devcontainer CLI
        run: npm install --global @devcontainers/cli

      - name: Testing global scenarios
        run: devcontainer features test --global-scenarios-only .
